
name: BUILD on Sailfish OS 5.0.0.43



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
    
      - name: Prepare
        run: mkdir output
      
      - name: Build armv7hl
        id: build_armv7hl
        uses: n1cetatoooo/angelfish
        with:
          release: 5.0.0.43
          arch: armv7hl
        
      - name: Build i486
        id: build_i486
        uses:  n1cetatoooo/angelfish
        with:
          release: 5.0.0.43
          arch: i486

      - name: Build aarch64
        id: build_aarch64
        uses:  n1cetatoooo/angelfish
        with:
          release: 5.0.0.43
          arch: aarch64
      
      - name: Upload build result
        uses:  n1cetatoooo/angelfish
        with:
          name: rpm-build-result
          path: RPMS
